### ISSUE TITLE
BIND stop working

### ISSUE THREAD

**Issue by supernrm** [mikaku/Monitorix#9] opened 2013-03-29 17:05 UTC
After 15 min. of working stats from BIND, monitorix stop make graphs.

Fri Mar 29 17:59:00 2013 - main::ALRM_handler: bind_update(): Can't use string ("ANY") as a HASH ref while "strict refs" in use at /usr/lib/monitorix/bind.pm line 273.

Fri Mar 29 18:00:01 2013 - main::ALRM_handler: bind_update(): Can't use string ("ANY") as a HASH ref while "strict refs" in use at /usr/lib/monitorix/bind.pm line 273.

**Comment by mikaku** [comment] 2015-10-06 13:22
I've not seen problems anymore and I'm unable to reproduce it, therefore I'll close this issue.
Please, re-open it if the problems continue.

**Closed by mikaku** 2015-10-06 13:22 UTC
Labels: bug
