### ISSUE TITLE
Process statistics, how to monitory python applications 

### ISSUE THREAD

**Issue by frollic** [mikaku/Monitorix#187] opened 2017-07-03 09:22 UTC
Hi,

not really a bug, just need to know if it's doable, or how ... 

I have an python application  running on my Fedora system.
If you execute "ps -eo pid,comm,command", it lists as 
/usr/bin/python -OO ./somthing.py -c something.ini

Obviously, if I enter "python", as the process in the conf of monitorix, 
I can't be sure which python process that will get monitored (assuming 
I've got more than one). 

How should it be set up ? does the conf support "str ing s", or wildcards
for string matching in the process list ? 

thank you for a great application

**Comment by mikaku** [comment] 2017-07-03 09:32
@frollic, some time ago I merged the #136 pull request that should solve that situation.

So you can put the whole string in the `list` option, and Monitorix should be able to find it and monitor it.
Just let me know.

**Comment by frollic** [comment] 2017-07-03 10:22
Cool!

OK, so that works, with the first part of the string, what about the desc - 
seems the matching doesn't work there, nor the full string .... ?

I searched the issue list, but didn't find this one, sorry for double posting :(

**Comment by mikaku** [comment] 2017-07-03 11:20
Yeah, in the `<desc>` section the problem is not so easy to solve.

I'm affraid this is not supported by the Config::General Perl module, and Monitorix hasn't solved it in no other way either, sorry.

**Comment by frollic** [comment] 2017-07-03 11:51
OK, 

thnx for explaining, much appreciated.

**Closed** 2017-07-05 09:36 UTC
