### ISSUE TITLE
Mariadb, unexpected error in mysql_init()

### ISSUE THREAD

**Issue by sfatula** [mikaku/Monitorix#236] opened 2019-04-17 04:35 UTC
Is there a required package I may be missing perhaps? In the monitorix log file, when trying to use mysql.pm (actually vs mariadb 10.1), I get this line in the log file and the graph page is empty:

WARNING: unexpected errors in function mysql_init().

It doesn't really give much of a hint as far as what may be wrong. 

The section in the config file is:

```
<mysql>
	conn_type	= socket
	list		= /var/run/mysqld/mysqld.sock
	<desc>
		localhost = 3306,monitorix,somepassword
	</desc>
</mysql>
```

This is on xubuntu 18.10. I have verified I can log in as that user (monitorix) via socket.

**Comment by mikaku** [comment] 2019-04-17 06:06
As stated in the Monitorix web site, Debian derivatives (as Xubuntu looks like), comes with an extra configuration file in `/etc/monitorix.d/`.

Please, check if that extra configuration file exists, and if so, set it up accordingly.

You my also check in the Monitorix log file, if it's loading such extra configuration file.

**Comment by sfatula** [comment] 2019-04-17 06:43
Yep, and I have removed said Debian file. The only file in conf.d is mine. And, mine has the lines showm in the OP.

**Comment by mikaku** [comment] 2019-04-17 06:44
Now, just restart Monitorix and check the log file for any error.

**Comment by sfatula** [comment] 2019-04-17 06:48
I think you misunderstand, that was done long ago, there is no such file, I didn't just remove it in other words. So, long before the OP, the file was gone and the error I posted is what is in the log file.

**Comment by mikaku** [comment] 2019-04-17 06:50
Sorry, I don't know what is *OP*, and can you, please, restart Monitorix and paste here in its log file after 5 minutes running?

Thanks.

**Comment by sfatula** [comment] 2019-04-17 07:04
OP = my Original Post. Sure, will restart it again. But this was all done before I opened this issue was all I was trying to say. There is, and was, no debian file since a minute after installing monitorix as I of course read the doc and have used monitorix for years, just on a different platform, xubuntu version, etc. You can ignore the MacMojave error as that virtual machine is not always running. 

Here's the log file:

```
Wed Apr 17 01:59:28 2019 - Starting Monitorix version 3.11.0 (pid 5330).
Wed Apr 17 01:59:28 2019 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Wed Apr 17 01:59:28 2019 - Loading extra configuration file '/etc/monitorix/conf.d/00-steve.conf'.
Wed Apr 17 01:59:28 2019 - Initializing graphs.
Wed Apr 17 01:59:28 2019 - WARNING: unexpected errors in function mysql_init().
Wed Apr 17 01:59:28 2019 - Generating the 'index.html' file.
Wed Apr 17 01:59:28 2019 - Started HTTP built-in server (pid 5374).
Wed Apr 17 01:59:28 2019 - Ok, ready.
error: failed to get domain 'MacMojave'
error: Domain not found: no domain with matching name 'MacMojave'
Failed to read /var/log/exim/mainlog: No such file or directory**** No valid log lines read
Wed Apr 17 01:59:28 2019 - WARNING: the HTTP built-in server has authentication disabled.
HTTPServer: You can connect to your server at http://localhost:8280/
error: failed to get domain 'MacMojave'
error: Domain not found: no domain with matching name 'MacMojave'
Failed to read /var/log/exim/mainlog: No such file or directory**** No valid log lines read
error: failed to get domain 'MacMojave'
error: Domain not found: no domain with matching name 'MacMojave'
Failed to read /var/log/exim/mainlog: No such file or directory**** No valid log lines read
Not a HASH reference at /usr/lib/monitorix/mysql.pm line 491.
```

**Comment by mikaku** [comment] 2019-04-17 07:58
I'm trying to reproduce the same error, but I still don't get it.
Can you, please, paste the `<mysql>` section of the main configuration file?

**Comment by IzzySoft** [comment] 2019-04-17 08:32
@mikaku the `<mysql>` section was quoted in the OP (original/opening post – i.e. the one this issue was created with). I've checked the socket path, and it's the one used by Debian (and contained in the Debian specific config file). Only difference I see is in the `<description>` element, but that shouldn't be relevant for socket IIRC.

**Comment by IzzySoft** [comment] 2019-04-17 08:52
Ah sorry, my bad – I was misreading your request was for the **main** config file. The Debian config only overrides part of the `<mysql>` block and you need the remaining part.

**Comment by sfatula** [comment] 2019-04-17 14:44
Here it is from monitorix.conf, which has not been modified since the apt install:

```
# MYSQL graph
# -----------------------------------------------------------------------------
<mysql>
        conn_type = host
        list = localhost
#       list = /var/lib/mysql/mysql.sock
        <desc>
                localhost = 3306, user, secret
        </desc>
        rigid = 0, 2, 0, 0, 0, 0
        limit = 100, 100, 100, 100, 100, 100
</mysql>
```

**Comment by mikaku** [comment] 2019-04-17 15:11
Several things:

> The desc element has to be changed since the doc says to create a new user with no access to any databases

Well, this is only a security advice, in order to avoid people using 'root' or any other privileged user for the solely task of getting information. The `<desc>` element seems is not the problem here.

> Regarding missing mysql.pm (or can't find it), note this line from the log file:
Not a HASH reference at /usr/lib/monitorix/mysql.pm line 491.
I would think that means it can find it. Have not moved anything around

You might have right here, but not entirely. I mean, Monitorix consists of mainly two programs: `/usr/bin/monitorix` (the collector), and the `/var/lib/monitorix/www/cgi/monitorix.cgi` (the CGI). The error you are referring comes from the CGI, it complaints because you didn't include the options `rigid` and `limit` in your `/etc/monitorix/conf.d/00-steve.conf` file.

The error `WARNING: unexpected errors in function mysql_init()` though, comes from the collector during the initialization of every enabled graph. And the **only** case where I can reproduce it is when I change the name of the `mysql_init()` function by anything (i.e: `mmysql_init()`).

Can you please, ~check~ ... ~double~ ... triple check the `mysql.pm` file to see that it's exactly the same as the original in [GitHub](https://github.com/mikaku/Monitorix/blob/master/lib/mysql.pm)?.

PS: I hope your wife's surgery go well.

**Comment by sfatula** [comment] 2019-04-17 15:18
```
/usr/lib/monitorix# ls -l
total 1736
-rw-r--r-- 1 root root 15246 Mar 14 15:08 ambsens.pm
-rw-r--r-- 1 root root 50493 Mar 14 15:08 apache.pm
-rw-r--r-- 1 root root 37034 Mar 14 15:08 apcupsd.pm
-rw-r--r-- 1 root root 65963 Mar 14 15:08 bind.pm
-rw-r--r-- 1 root root 32862 Mar 14 15:08 chrony.pm
-rw-r--r-- 1 root root 30110 Mar 14 15:08 disk.pm
-rw-r--r-- 1 root root 14544 Mar 14 15:08 du.pm
-rw-r--r-- 1 root root  5790 Mar 14 15:08 emailreports.pm
-rw-r--r-- 1 root root 14373 Mar 14 15:08 fail2ban.pm
-rw-r--r-- 1 root root 47032 Mar 14 15:08 fs.pm
-rw-r--r-- 1 root root 24211 Mar 14 15:08 ftp.pm
-rw-r--r-- 1 root root 18635 Mar 14 15:08 gensens.pm
-rw-r--r-- 1 root root 26170 Mar 14 15:08 hptemp.pm
-rw-r--r-- 1 root root  8755 Mar 14 15:08 HTTPServer.pm
-rw-r--r-- 1 root root 22780 Mar 14 15:08 icecast.pm
-rw-r--r-- 1 root root 33454 Mar 14 15:08 int.pm
-rw-r--r-- 1 root root 14448 Mar 14 15:08 ipmi.pm
-rw-r--r-- 1 root root 34412 Mar 14 15:08 kern.pm
-rw-r--r-- 1 root root 33091 Mar 14 15:08 libvirt.pm
-rw-r--r-- 1 root root 22367 Mar 14 15:08 lighttpd.pm
-rw-r--r-- 1 root root 56743 Mar 14 15:08 lmsens.pm
-rw-r--r-- 1 root root 58155 Mar 14 15:08 mail.pm
-rw-r--r-- 1 root root 50180 Mar 14 15:08 memcached.pm
-rw-r--r-- 1 root root 58170 Mar 14 15:08 mongodb.pm
-rw-r--r-- 1 root root 11219 Mar 14 15:08 Monitorix.pm
-rw-r--r-- 1 root root 52404 Mar 14 15:08 mysql.pm
-rw-r--r-- 1 root root 23674 Mar 14 15:08 net.pm
-rw-r--r-- 1 root root 40484 Mar 14 15:08 netstat.pm
-rw-r--r-- 1 root root 33854 Mar 14 15:08 nfsc.pm
-rw-r--r-- 1 root root 51025 Mar 14 15:08 nfss.pm
-rw-r--r-- 1 root root 23097 Mar 14 15:08 nginx.pm
-rw-r--r-- 1 root root 23671 Mar 14 15:08 ntp.pm
-rw-r--r-- 1 root root 36544 Mar 14 15:08 nut.pm
-rw-r--r-- 1 root root 25897 Mar 14 15:08 nvidia.pm
-rw-r--r-- 1 root root 65771 Mar 14 15:08 pagespeed.pm
-rw-r--r-- 1 root root 25081 Mar 14 15:08 phpapc.pm
-rw-r--r-- 1 root root 21957 Mar 14 15:08 port.pm
-rw-r--r-- 1 root root 56407 Mar 14 15:08 process.pm
-rw-r--r-- 1 root root 24137 Mar 14 15:08 proc.pm
-rw-r--r-- 1 root root 21162 Mar 14 15:08 raspberrypi.pm
-rw-r--r-- 1 root root 39229 Mar 14 15:08 serv.pm
-rw-r--r-- 1 root root 57806 Mar 14 15:08 squid.pm
-rw-r--r-- 1 root root 36580 Mar 14 15:08 system.pm
-rw-r--r-- 1 root root 34721 Mar 14 15:08 tc.pm
-rw-r--r-- 1 root root 23114 Mar 14 15:08 traffacct.pm
-rw-r--r-- 1 root root 16762 Mar 14 15:08 user.pm
-rw-r--r-- 1 root root 43655 Mar 14 15:08 varnish.pm
-rw-r--r-- 1 root root 17785 Mar 14 15:08 verlihub.pm
-rw-r--r-- 1 root root 45424 Mar 14 15:08 wowza.pm
-rw-r--r-- 1 root root 40559 Mar 14 15:08 zfs.pm
```

wget -O mysql.git https://raw.githubusercontent.com/mikaku/Monitorix/master/lib/mysql.pm

diff mysql.git mysql.pm shows nothing, files are identical

**Comment by mikaku** [comment] 2019-04-18 08:44
@sfatula, what RRDtool version you have there?

**Comment by sfatula** [comment] 2019-04-18 13:10
1.7.0

**Comment by mikaku** [comment] 2019-04-18 15:07
I've never tested RRDtool 1.7, in fact I haven't even tested 1.6!
Do you think It would be possible if you can downgrade to RRDtool 1.4.x or 1.5.x?

**Comment by sfatula** [comment] 2019-04-18 19:54
Hmm, I thought rrdtool was for the gui, not the collector where the issue is?

**Comment by mikaku** [comment] 2019-04-18 20:18
> Hmm, I thought rrdtool was for the gui, not the collector where the issue is?

RRDtool helps to the collector to save in the `.rrd` files the values  gathered, and it also helps to the CGI to render the graphs.

I'd like to know if you can downgrade temporarily your RRDtool to a lower version (1.4 or 1.5) just to see if there is an incompatibility with a newer RRDtool version.

**Comment by sfatula** [comment] 2019-04-18 20:24
It may be somewhat doable, will have to see what packages might break due to dependency requirements. ubuntu has been shipping rrdtool > 1.5 since April 2018 in xenial 18.04. I'll have to defer this task as I have to resolve the multiple monitor bug in 18.10 first. That will be either by going to 19.04, or, be installing 18.04 from scratch.

**Comment by mikaku** [comment] 2019-04-19 08:12
I've managed to create a virtual machine and installed Fedora 29 on it. Fedora 29 comes with RRDtool v1.7.1, so I thought that it would be good testing field to see if I can reproduce your issue.

The result is no; all is working fine with RRDtool 1.7.1. :disappointed: 

Nevertheless, I've included some fixes in your `/etc/monitorix/conf.d/00-steve.conf` because it wasn't correctly well configured. Your original file yielded the following errors:

```
Fri Apr 19 09:53:10 2019 - Starting Monitorix version 3.11.0 (pid 4051).
Fri Apr 19 09:53:10 2019 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Fri Apr 19 09:53:10 2019 - Loading extra configuration file '/etc/monitorix/conf.d/00-steve.conf'.
Fri Apr 19 09:53:10 2019 - Initializing graphs.
Fri Apr 19 09:53:10 2019 - Generating the 'index.html' file.
Fri Apr 19 09:53:10 2019 - WARNING: the HTTP built-in server has authentication disabled.
HTTPServer: You can connect to your server at http://localhost:8080/
Fri Apr 19 09:53:10 2019 - Started HTTP built-in server (pid 4101).
Fri Apr 19 09:53:10 2019 - Ok, ready.
Use of uninitialized value in split at /usr/lib/monitorix/mysql.pm line 193.
Use of uninitialized value in split at /usr/lib/monitorix/mysql.pm line 194.
Use of uninitialized value in split at /usr/lib/monitorix/mysql.pm line 195.
```

This is because Monitorix was unable to find `/var/run/mysqld/mysqld.sock` as a key in `<desc>`.

So, I changed your configuration file to this one:

```
<mysql>
	conn_type	= socket
	list		= /var/lib/mysql/mysql.sock
	<desc>
		/var/lib/mysql/mysql.sock = 3306,monitorix,somepassword
	</desc>
</mysql>
```

Now, after restarting Monitorix, there are no errors at all:

```
Fri Apr 19 10:01:45 2019 - Starting Monitorix version 3.11.0 (pid 5717).
Fri Apr 19 10:01:45 2019 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Fri Apr 19 10:01:45 2019 - Loading extra configuration file '/etc/monitorix/conf.d/00-steve.conf'.
Fri Apr 19 10:01:45 2019 - Initializing graphs.
Fri Apr 19 10:01:46 2019 - Generating the 'index.html' file.
Fri Apr 19 10:01:46 2019 - Started HTTP built-in server (pid 5767).
Fri Apr 19 10:01:46 2019 - Ok, ready.
Fri Apr 19 10:01:46 2019 - WARNING: the HTTP built-in server has authentication disabled.
HTTPServer: You can connect to your server at http://localhost:8080/
```

**Comment by sfatula** [comment] 2019-04-20 02:43
That's what I have in mine, maybe I changed it since the original post (OP). Didn't think I did, perhaps the upgrade to 19.04 did something. 

```
<mysql>
        conn_type = socket
        list = /var/run/mysqld/mysqld.sock
        <desc>
                /var/run/mysqld/mysqld.sock = 3306, monitorix, somepassword
        </desc>
</mysql>
```

In any case, no change for me, same result. 

```
Fri Apr 19 21:41:02 2019 - Starting Monitorix version 3.11.0 (pid 9907).
Fri Apr 19 21:41:02 2019 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Fri Apr 19 21:41:02 2019 - Loading extra configuration file '/etc/monitorix/conf.d/00-steve.conf'.
Fri Apr 19 21:41:02 2019 - Initializing graphs.
Fri Apr 19 21:41:02 2019 - WARNING: unexpected errors in function mysql_init().
Fri Apr 19 21:41:02 2019 - Generating the 'index.html' file.
Fri Apr 19 21:41:02 2019 - WARNING: the HTTP built-in server has authentication disabled.
HTTPServer: You can connect to your server at http://localhost:8280/
Not a HASH reference at /usr/lib/monitorix/mysql.pm line 491.
```

Does the mysql_init error refer to your function called mysql_init, or, the mysql function?

**Comment by mikaku** [comment] 2019-04-20 06:45
> Does the mysql_init error refer to your function called mysql_init, or, the mysql function? Note the actual mariadb path on my system has the d after mysql and is correct.

Yes, the error `WARNING: unexpected errors in function mysql_init().` comes from the Monitorix collector (`/usr/bin/monitorix`), when it initializes (calls every `_init()` function) of all enabled graphs. In these `_init()` functions there is no way to return a bad value to show that message, it should be something that affects Perl or RRDtool directly, that's why I told you that the only way I can reproduce this error is changing the name of the `_init()` function, this is clearly an unexpected Perl problem and the collector shows that error.

That's why I though that it could also be a problem with your so new RRDtool version (untested then by me).

Now I have another question, is the `mysql` the only enabled graph or do you have others graphs enabled without any WARNING?

**Comment by sfatula** [comment] 2019-04-20 22:50
Many enabled graphs, at least a dozen. All work. I suspect it has something to do with the software loaded in newer ubuntu versions, later perl, later everything. As I will now be back on 18.04, I will undoubtedly not have the issue since it already works fine on another 18.04 machine. So, not much for you to do except if someone else gets the error, it will be a hint that it's later ubuntus that have the issue.

**Comment by mikaku** [comment] 2019-04-21 08:16
It's really strange why the rest of graph are not affected by the problem, only the `mysql.pm` module.

Also, you might want to try to include some lines like `print "1\n";`, `print "2\n";`, etc., here and there in the `mysql_init()` function to see in which point it breaks. That would provide more information.

By the way, Fedora 29 has Perl v5.28.1, what version has your 18.10?

**Comment by sfatula** [comment] 2019-04-22 00:21
As mentioned, I do not have 18.10 anynore, or 19.04 which is where I was several messages ago. I am on 18.04 due to the bugs I found in the OS. So, I don't know the answer any more. That's why I suggested "So, not much for you to do except if someone else gets the error, it will be a hint that it's later ubuntus that have the issue.". i.e., you may as well close this. Would have gladly helped but the multiscreen bugs in ubuntu 18.10+ were not useable for my purposes.

**Comment by mikaku** [comment] 2019-04-22 06:51
OK, let's close this, and we'll see if someone reopens it in the future.
Thanks!

**Closed by mikaku** 2019-04-22 06:51 UTC
