### ISSUE TITLE
Monitor log-file is filling up with WARNING: unable to connect to HTTP built-in server 'http://localhost:8080/monitorix'.

### ISSUE THREAD

**Issue by Sweepr** [mikaku/Monitorix#257] opened 2019-10-22 09:24 UTC
Logfile is filling up with this:

Tue Oct 22 10:59:00 2019 - WARNING: unable to connect to HTTP built-in server 'http://localhost:8080/monitorix'.
Tue Oct 22 10:59:00 2019 - Restarted HTTP built-in server (pid 5409).
HTTPServer: You can connect to your server at http://localhost:8080/

curl -v localhost:8080/monitorix
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /monitorix HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:8080
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 401 Access Denied
< WWW-Authenticate: Basic realm="Monitorix: Restricted access"
< Content-Length: 0
<
* Closing connection #0

I have Auth enabled, is that the reason ?

How can i prevent the logfile filling up with this warning?

**Comment by mikaku** [comment] 2019-10-22 09:32
Hi,

Yes, it has been fixed in the #249 issue.

You might want to download the latest [monitorix](https://github.com/mikaku/Monitorix/blob/master/monitorix) version and overwrite your own, if you don't want to wait for the next Monitorix release.

Thanks.

**Comment by Sweepr** [comment] 2019-10-22 09:46
:+1: Great, thnx.. ! closing

**Closed** 2019-10-22 09:46 UTC

**Comment by atomGit** [comment] 2020-01-02 14:41
i'm getting essentially the same thing, except i'm running on :8088...

```
HTTPServer: You can connect to your server at http://localhost:8088/
Thu Jan  2 06:41:01 2020 - WARNING: unable to connect to HTTP built-in server 'http://localhost:8088/monitorix'.
```

```
# lsof -i:8088
COMMAND     PID   USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
monitorix 11231 nobody    3u  IPv4 1076896446      0t0  TCP *:radan-http (LISTEN)
```

```
Name        : monitorix
Arch        : noarch
Version     : 3.11.0
Release     : 1.el7
Size        : 1.8 M
Repo        : installed
From repo   : epel
```

**Comment by mikaku** [comment] 2020-01-02 14:53
@atomGit, yes this has already been fixed in the development version, so it will be fixed in the next release of Monitorix.

As I said, if you don't want to wait for the next version, you might want to download the latest `monitorix` version and overwrite your own.

Thanks.

**Comment by atomGit** [comment] 2020-01-02 16:07
oh, i'm sorry, i mistakenly thought it was fixed in 3.11.0

**Comment by JackySw** [comment] 2023-12-19 12:10
I got v3.15.0 but also still this problem.

_WARNING: HTTP built-in server not responding at 'http://myserver.com:8090/monitorix'._

But the URL is 100% correct and responsive. What could be it?

The httpd server always becomes unresponsive after 3 or 4 days or so. I cannot figure out why and this auto responsive check could fix it in the time-being.

**Comment by mikaku** [comment] 2023-12-19 13:27
I've the latest version (`perl-HTTP-Server-Simple-0.52-21.fc39.noarch`) and I almost don't see this message except on very  poradic times when this web server is somehow abused from an outside script.

Are you using the latest version of this Perl module?

**Comment by JackySw** [comment] 2023-12-19 13:36
Thank you. Yes, I got 0.52.

**Comment by JackySw** [comment] 2023-12-19 13:49
Ok, this is interesting. I got:

```
<httpd_builtin>
...
hosts_allow = localhost, 127.0.0.1, 123.123.123.123
autocheck_responsiveness = y
....
</httpd_builtin>
```
Assuming this would be ok for IP access for localhost and myself. But it seems that the autocheck responsiveness cannot be performed because the result from checking the URL still gives a 403 access forbidden response. So instead of 'localhost' I added the IP address of the server in _hosts_allow_ and now it works.

Interesting. Is this the behavior that was intended?

**Comment by Sweepr** [comment] 2023-12-19 14:06
127.0.0.1 is the IP address assigned to the "loopback" or local-only interface. This is a "fake" network adapter that can only communicate within the same host. It's often used when you want a network-capable application to only serve clients on the same host. A process that is listening on 127.0.0.1 for connections will only receive local connections on that socket.

"localhost" is normally the hostname for the 127.0.0.1 IP address. It's usually set in /etc/hosts, you can use it just like any other hostname, try pinging localhost and see how it resolves to 127.0.0.1.

**Comment by mikaku** [comment] 2023-12-19 14:07
Well, if the `host` option in `<httpd_builtin>` is not defined, then it should bind Monitorix to all interfaces (including localhost).

Please, check with `netstat -ltnp` or `ss -ltnp` if your Monitorix web server is correctly bound to 0.0.0.0.

**Comment by JackySw** [comment] 2023-12-19 14:20
Thanks Sweepr for explaining this. 
Mikaku, no it is not bound to 0.0.0.0. I do indeed use the `host ` option.

**Comment by mikaku** [comment] 2023-12-19 15:10
@JackySw: so it's all fixed now?

**Comment by mikaku** [comment] 2023-12-19 18:54
I've seen that in some systems binding to 0.0.0.0 does not always work for some reason. Maybe this is your case.
Anyway, glad to know you managed to solve it, and also glad you are enjoying Monitorix.
