### ISSUE TITLE
Pango Errors

### ISSUE THREAD

**Issue by StephenAtty** [mikaku/Monitorix#194] opened 2017-10-29 21:28 UTC
I upgraded to the version as shipped from the Izzy repository.

Now I get errors when I view the web page:

(process:30665): Pango-WARNING **: error opening config file '/root/.config/pango/pangorc': Permission denied
(process:30668): Pango-WARNING **: error opening config file '/root/.config/pango/pangorc': Permission denied
(process:30670): Pango-WARNING **: error opening config file '/root/.config/pango/pangorc': Permission denied

It doesn't do it with the tar archive - so its something that's got added in when its been built.

**Comment by mikaku** [comment] 2017-10-30 09:10
Looks like something related to the dependences of RRDtool in your system.
Let's see if @IzzySoft can shed more light on this.

**Comment by IzzySoft** [comment] 2017-10-30 12:53
Afraid I cannot. I didn't see those errors on the webpage on my systems. But what I find strange is: @StephenAtty what kind of config files reside inside `/root`? Are you sure that belongs there? And if so, check the permissions. @mikaku I don't think that part of Monitorix runs as root? Especially the web service I wouldn't expect to.

Summed up: I don't think this is an issue in Monitorix or in my Debian package, but rather a configuration/setup problem.

**Comment by mikaku** [comment] 2017-10-30 14:44
> @mikaku I don't think that part of Monitorix runs as root? Especially the web service I wouldn't expect to

Only the stats collector (the daemon) runs as root.
The HTTP built-in server runs as *nobody*, at least in RHEL based systems. I assume the same for the rest.

> Summed up: I don't think this is an issue in Monitorix or in my Debian package, but rather a configuration/setup problem.

I'm agree with that.

**Comment by StephenAtty** [comment] 2017-10-30 19:28
The odd thing is that if I do 
make install-debian-all
from the tarball and basically install the tarball over the repository version then it works with no problems at all
if I then re-install from the repository then I get the problems if I view the webpages after doing a service monitorix start

doing a service start monitorix  results in:

root      3566     1  0 Oct29 ?        00:00:50 /usr/bin/monitorix -c /etc/monitorix/monitorix.conf -p /var/run/monitorix.pid
nobody    3599  3566  0 Oct29 ?        00:00:03 monitorix-httpd listening on 8080


The server is a headless workstation with no GUI on it all, I've no idea why pango is even involved in this  - I've no pango configuration directories under root and I 

If it was something in the packages loaded as dependencies for the repository version then I can't understand why doing the install from the tarball makes the problem go away.

**Comment by IzzySoft** [comment] 2017-10-31 01:45
I certainly did not introduce any stuff into the package. I just created it from the sources, using the make file. As I wrote, I'm using it at two machines here myself, and cannot reproduce the issue. Could you check the configs if that strange location appears somewhere? Maybe you've just got a module enabled that I don't use (and explicitly disabled in my "overlaying config")?

**Comment by mikaku** [comment] 2017-10-31 09:00
@StephenAtty, one possibility is that the Debian package management has setup different permissions in the directory were the .png files are created, and now, the HTTP built-in server is unable to write there.

So, please, make sure that the directory `/var/lib/monitorix/www/imgs/` and the files created in (if any) are writable by the user *nobody*.

Just let us know.

**Comment by IzzySoft** [comment] 2017-11-01 18:32
@mikaku the file complained on is a different one, see the initial post:

    (process:30665): Pango-WARNING **: error opening config file '/root/.config/pango/pangorc': Permission denied

Something wants to access a Pango config file stored in root's home. But the only occurence of the term "pango" I can find in my monitorix tree is in `docs/Changes`. Can't find it in my build scripts either.

**Comment by mikaku** [comment] 2017-11-02 07:29
@IzzySoft, yeah just wanted to make sure that permissions are OK.

@StephenAtty are you using the HTTP built-in server in all cases? I mean, perhaps after `tar.gz` installation you are using Apache, but after repository installation you are using the Monitorix HTTP built-in server. Or in the other way around.

**Comment by StephenAtty** [comment] 2017-11-02 18:13
I've got the izzysoft file extracted - what I'll do is replace bits of the tarball install with the stuff from the izzysoft file and see if I can make it go wrong.

Its always using the built in http service.

**Comment by mikaku** [comment] 2017-11-14 12:04
@StephenAtty, any news on this?

**Comment by StephenAtty** [comment] 2017-11-14 19:10
I've been on call at work and working on my boat, so I've not had time to try the gradual replacement of the code. Will look at it tomorrow.

**Comment by mikaku** [comment] 2018-02-12 17:32
@StephenAtty, There's no news from you since Novembre, I assume you already fixed it.
We can close it?

**Comment by StephenAtty** [comment] 2018-02-12 18:11
Sorry - I've actually stopped using Monitorix - meant to come in and close the ticket

**Closed** 2018-02-13 07:29 UTC
